Add fix for Snowflake cacert issue
rstudio/sol-eng-demo-server pull request #67
Opened 2021-04-08 15:24 UTC by blairj09

There's a current issue with the Snowflake driver that prevents it from working properly without first modifying `/opt/rstudio-drivers/snowflake/bin/lib/rstudio.snowflakeodbc.ini`. This PR introduces a fix for the issue until it is resolved upstream.

2021-04-08 15:31 UTC, blairj09 commented
Confirmed fix:

2021-04-13 12:48 UTC, colearendt requested changes
Just the one issue! Thanks for fixing this!

2021-04-13 12:48 UTC, colearendt commented on Dockerfile_multi
>      sed -i '/Installer = RStudio$/cInstaller = RStudio Pro Drivers' /etc/odbcinst.ini
missing a line-extension here
```suggestion
    sed -i '/Installer = RStudio$/cInstaller = RStudio Pro Drivers' /etc/odbcinst.ini && \
```

2021-04-13 12:48 UTC, colearendt commented on Dockerfile
> +    sed -i '/Installer = RStudio$/cInstaller = RStudio Pro Drivers' /etc/odbcinst.ini && \
Actually, do we still need this?

2021-04-13 16:29 UTC, colearendt approved these changes
🎉

2021-04-13 16:35 UTC, merged